kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "webserver-controller"
spec:
  replicas: 2
  selector:
    name: "webserver"
  template:
    spec:
      containers:
        - name: "webserver"
          image: "webwithdb"
          ports:
            - containerPort: 80
    metadata:
      labels:
        name: "webserver"
        uses: db
      selectorname: "webserver"
  labels:
    name: "webserver"
